vim.keymap.set("n", "<leader>pi", "<Cmd>Lazy install<CR>", { desc = "Install plugins" })
vim.keymap.set("n", "<leader>pc", "<Cmd>Lazy clean<CR>", { desc = "Clean plugins" })
vim.keymap.set("n", "<leader>pu", "<Cmd>Lazy update<CR>", { desc = "Update plugins" })
vim.keymap.set("n", "<leader>td", "<Cmd>TodoTelescope keywords=TODO,FIX<CR>", { desc = "Show TODO picker" })
vim.keymap.set("n", "<leader>th", "<Cmd>Telescope help_tags<CR>", { desc = "Search help" })
vim.keymap.set("n", "<leader>tk", "<Cmd>Telescope keymaps<CR>", { desc = "Search keymaps" })
vim.keymap.set("n", "<leader>tr", "<Cmd>Telescope resume<CR>", { desc = "Resume last search" })
vim.keymap.set("n", "<leader>tc", "<Cmd>Telescope commands<CR>", { desc = "Search commands" })
vim.keymap.set("n", "<C-p>", "<Cmd>GFiles<CR>", { desc = "Search git files" })
vim.keymap.set("n", "<leader>pf", "<Cmd>Files<CR>", { desc = "Search files" })
vim.keymap.set("n", "<leader>r", "<Cmd>Rg<CR>", { desc = "Search with ripgrep" })
vim.keymap.set("n", "<leader>tf", "<Cmd>Telescope find_files<CR>", { desc = "Find files" })
vim.keymap.set("n", "<leader>tg", "<Cmd>Telescope live_grep<CR>", { desc = "Live grep" })
vim.keymap.set("n", "<leader>fb", "<Cmd>Telescope file_browser path=%:p:h select_buffer=true<CR>", { desc = "Open file browser" })
vim.keymap.set("n", "<leader>b", "<Cmd>Telescope buffers<CR>", { desc = "Show buffers" })

-- Git
vim.keymap.set("n", "<leader>gs", "<Cmd>Git<CR>", { desc = "Open Git status" })
vim.keymap.set("n", "<leader>gl", "<Cmd>GcLog<CR>", { desc = "Show Git log" })
vim.keymap.set("n", "<leader>gP", "<Cmd>Git push<CR>", { desc = "Push current branch" })
vim.keymap.set("n", "<leader>gp", "<Cmd>Git pull<CR>", { desc = "Pull current branch" })
vim.keymap.set("n", "<leader>ga", "<Cmd>Gwrite<CR>", { desc = "Stage current file" })
vim.keymap.set("n", "<leader>gg", "<Cmd>LazyGit<CR>", { desc = "Open LazyGit" })
vim.keymap.set("n", "<leader>gv", "<Cmd>DiffviewOpen<CR>", { desc = "Open Diffview" })
vim.keymap.set("n", "<leader>gh", "<Cmd>DiffviewFileHistory %<CR>", { desc = "Show file history" })
vim.keymap.set("n", "<leader>gq", "<Cmd>DiffviewClose<CR>", { desc = "Close Diffview" })
vim.keymap.set("n", "<leader>u", "<Cmd>UndotreeToggle<CR>", { desc = "Toggle undo tree" })

vim.keymap.set("n", "<leader>cf", "<Cmd>Format<CR>", { desc = "Format current buffer" })
vim.keymap.set("n", "<leader>af", "<Cmd>FormatToggle<CR>", { desc = "Toggle format on save" })

-- Diagnostics
vim.keymap.set("n", "<leader>xx", "<Cmd>Trouble diagnostics toggle<CR>", { desc = "Toggle diagnostics list" })
vim.keymap.set("n", "<leader>xX", "<Cmd>Trouble diagnostics toggle filter.buf=0<CR>", { desc = "Toggle buffer diagnostics" })
vim.keymap.set("n", "<leader>cs", "<Cmd>Trouble symbols toggle focus=false<CR>", { desc = "Toggle document symbols" })
vim.keymap.set("n", "<leader>cl", "<Cmd>Trouble lsp toggle focus=false win.position=right<CR>", { desc = "Toggle LSP locations" })
vim.keymap.set("n", "<leader>xL", "<Cmd>Trouble loclist toggle<CR>", { desc = "Toggle location list" })
vim.keymap.set("n", "<leader>xQ", "<Cmd>Trouble qflist toggle<CR>", { desc = "Toggle quickfix list" })
