local map = vim.keymap.set

map("n", "<leader>pv", "<Cmd>bel vsplit<CR><Cmd>Oil<CR>", { desc = "Browse files in vertical split" })
map("n", "<leader>ph", "<Cmd>bel split<CR><Cmd>Oil<CR>", { desc = "Browse files in horizontal split" })
map("n", "-", "<Cmd>Oil<CR>", { desc = "Open parent directory" })

map("n", "<leader>pi", "<Cmd>Lazy install<CR>", { desc = "Install plugins" })
map("n", "<leader>pc", "<Cmd>Lazy clean<CR>", { desc = "Clean plugins" })
map("n", "<leader>pu", "<Cmd>Lazy update<CR>", { desc = "Update plugins" })

map("n", "<leader>td", "<Cmd>TodoTelescope keywords=TODO,FIX<CR>", { desc = "Todo comments" })

map("n", "<C-p>", "<Cmd>GFiles<CR>", { desc = "Git files" })
map("n", "<leader>pf", "<Cmd>Files<CR>", { desc = "Find files" })
map("n", "<leader>r", "<Cmd>Rg<CR>", { desc = "Ripgrep" })
map("n", "<leader>tf", "<Cmd>Telescope find_files<CR>", { desc = "Telescope files" })
map("n", "<leader>tg", "<Cmd>Telescope live_grep<CR>", { desc = "Telescope grep" })
map("n", "<leader>fb", "<Cmd>Telescope file_browser path=%:p:h select_buffer=true<CR>", { desc = "File browser" })
map("n", "<leader>b", "<Cmd>Telescope buffers<CR>", { desc = "Buffers" })

map("n", "<leader>gs", "<Cmd>Git<CR>", { desc = "Git status" })
map("n", "<leader>gl", "<Cmd>GcLog<CR>", { desc = "Git log" })
map("n", "<leader>gP", "<Cmd>Git push<CR>", { desc = "Git push" })
map("n", "<leader>gp", "<Cmd>Git pull<CR>", { desc = "Git pull" })
map("n", "<leader>ga", "<Cmd>Gwrite<CR>", { desc = "Git add current file" })
map("n", "<leader>gg", "<Cmd>LazyGit<CR>", { desc = "LazyGit" })
map("n", "<leader>gv", "<Cmd>DiffviewOpen<CR>", { desc = "Open diff view" })
map("n", "<leader>gh", "<Cmd>DiffviewFileHistory %<CR>", { desc = "File history" })
map("n", "<leader>gq", "<Cmd>DiffviewClose<CR>", { desc = "Close diff view" })
map("n", "<leader>u", "<Cmd>UndotreeToggle<CR>", { desc = "Undo tree" })
map("n", "<leader>cc", "<Cmd>CopilotChat<CR>", { desc = "Copilot chat" })
map("n", "<leader>cf", "<Cmd>Format<CR>", { desc = "Format buffer" })
map("n", "<leader>af", "<Cmd>FormatToggle<CR>", { desc = "Toggle autoformat" })

map("n", "<leader>xx", "<Cmd>Trouble diagnostics toggle<CR>", { desc = "Diagnostics" })
map("n", "<leader>xX", "<Cmd>Trouble diagnostics toggle filter.buf=0<CR>", { desc = "Buffer diagnostics" })
map("n", "<leader>cs", "<Cmd>Trouble symbols toggle focus=false<CR>", { desc = "Symbols" })
map("n", "<leader>cl", "<Cmd>Trouble lsp toggle focus=false win.position=right<CR>", { desc = "LSP definitions" })
map("n", "<leader>xL", "<Cmd>Trouble loclist toggle<CR>", { desc = "Location list" })
map("n", "<leader>xQ", "<Cmd>Trouble qflist toggle<CR>", { desc = "Quickfix list" })